package dev.nemi.aoharu;

import dev.nemi.aoharu.prime.Role;
import dev.nemi.aoharu.prime.User;
import dev.nemi.aoharu.repository.users.UserRepo;
import lombok.extern.log4j.Log4j2;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.crypto.password.PasswordEncoder;

@SpringBootTest
@Log4j2
public class UsersTest {

  private String[] usernames = {
    "Vickie.Lind",
    "Aubree82",
    "Mavis.Sawayn65",
    "Lamont86",
    "Aurelie_Lindgren36",
    "Enid17",
    "Bennett.Schowalter56",
    "Joshuah.Bins41",
    "Savannah_Ryan52",
    "Cathryn.Dickens",
    "Colt_Hammes",
    "Lulu.Corkery",
    "Eldon.Stracke72",
    "Victor.Strosin",
    "Hope.Langworth51",
    "Jonathan_Batz",
    "Alphonso.Mayert",
    "Blake_Marvin",
    "Odie.Glover",
    "Alysson_Rosenbaum73",
    "Coleman73",
    "Olen.Barton19",
    "Martin11",
    "Yadira.Wiza",
    "Alfonzo.Bartoletti-Spencer0",
    "Sandra.Wilderman84",
    "Ona_Hilpert10",
    "Lucius12",
    "Turner_Gutmann69",
    "Emile_Koss",
    "Raoul9",
    "Lenna_Lehner53",
    "Maximillia84",
    "Herbert_Berge45",
    "Frederik_Murray",
    "Gonzalo_Hyatt",
    "Keon.Koelpin84",
    "Parker35",
    "Lynn64",
    "Ambrose.Marvin64",
    "Alek65",
    "Ola_Beier",
    "Josue_Fadel43",
    "Aurore_Dare",
    "Rafael_Greenholt",
    "Sanford_White",
    "Zelda82",
    "Alberta15",
    "Derrick_Moen-Terry",
    "Karen.Haley",
    "Anika.Aufderhar",
    "Davon_Baumbach",
    "Rahul4",
    "Vanessa.Torp82",
    "Demarco51",
    "Flavie40",
    "Liana85",
    "Danial13",
    "Herta15",
    "Emie_Casper75",
    "Adaline_Rowe64",
    "Miguel_Lakin3",
    "Mathilde_Hilpert29",
    "Albin79",
    "Della67",
    "Crawford.Larson60",
    "Enos_Kirlin50",
    "Sven.Shields",
    "Wiley.Rath",
    "Kay53",
    "Flavio.Ryan78",
    "Gino.Quitzon38",
    "Yasmin.Rowe34",
    "Vesta_MacGyver22",
    "Jodie.Stracke",
    "Hortense.Predovic",
    "Alba_Runolfsdottir",
    "Luella_Hessel0",
    "Marlon_Rolfson48",
    "Stephan.Larkin18",
    "Darian_Crooks77",
    "Waldo_Jenkins79",
    "Tyson_Brakus",
    "Treva_Gusikowski-Cummings",
    "Lauren_Cole-Herman98",
    "Jerad_Altenwerth22",
    "Simone.Miller",
    "George.Kulas",
    "Jade52",
    "Isidro_Ratke",
    "Robert_Nienow-Schmidt33",
    "Adrianna_Hackett",
    "Tom76",
    "Grant67",
    "Christophe53",
    "Mabelle.Stiedemann",
    "Antonette_Cole",
    "Weston75",
    "Hilton_Kessler21",
    "Noah71"
};

  private String[] emails = {
    "Moises.Larson@example.com",
    "Effie.Kemmer-Ullrich27@example.net",
    "Deonte.Schimmel89@example.org",
    "Jayde.Bahringer-Dicki2@example.net",
    "Corrine70@example.net",
    "Hazle_Schaefer@example.net",
    "Brayan_Jenkins@example.org",
    "Adrain50@example.org",
    "Joana.Wolf@example.net",
    "Daniella.Kertzmann@example.org",
    "Rick_Rutherford@example.org",
    "Pinkie_Konopelski28@example.net",
    "Zoe_Leannon@example.net",
    "Percy.Jakubowski-Upton@example.org",
    "Jaden35@example.net",
    "Virginie.McGlynn@example.com",
    "Rosalinda_Hammes@example.net",
    "Kian_Rohan49@example.com",
    "Marisol_McKenzie84@example.org",
    "Willa7@example.net",
    "Abbey.Nolan@example.com",
    "Joanne3@example.net",
    "Johnson.Weber@example.net",
    "Matilda.Wisozk52@example.org",
    "Ola.Koepp@example.com",
    "Ethelyn.Smith@example.org",
    "Forest_Streich@example.com",
    "Gunner24@example.net",
    "Kacie36@example.org",
    "Nicholas87@example.org",
    "Braxton.Kuhic58@example.org",
    "Marjorie.Lowe54@example.org",
    "Edgardo.Gulgowski52@example.org",
    "Gabrielle96@example.net",
    "Estella.Lueilwitz47@example.net",
    "Daniela.Bailey25@example.net",
    "Dejon11@example.net",
    "Alverta.Emard-Abshire@example.net",
    "Astrid.Brekke@example.org",
    "Anabelle.Waelchi@example.org",
    "Chandler_Wiegand@example.com",
    "Maximilian.Shanahan-Rosenbaum15@example.net",
    "Emelia.Lueilwitz88@example.com",
    "Guido12@example.net",
    "Thad.Brekke3@example.org",
    "Lola92@example.org",
    "Sebastian82@example.org",
    "Justice61@example.org",
    "May.Thompson@example.com",
    "Berta.Moore4@example.net",
    "Carissa_Jenkins@example.org",
    "Holly36@example.net",
    "Kylie.Wehner@example.org",
    "Eleonore_Watsica@example.org",
    "Mae_Parisian32@example.org",
    "Al67@example.com",
    "Percy_Schneider36@example.org",
    "Pearl63@example.com",
    "Otilia50@example.com",
    "Nico.Kohler54@example.net",
    "Seamus46@example.com",
    "Seamus_Cartwright@example.org",
    "Giovanny.Hamill12@example.net",
    "Guido61@example.net",
    "Erik52@example.com",
    "Winona.Durgan71@example.org",
    "Gabe_Heathcote@example.com",
    "Juliana54@example.org",
    "Camden.Rowe@example.org",
    "Flavie38@example.com",
    "Destiney_Treutel@example.org",
    "Taya.Leuschke80@example.com",
    "Bettye84@example.org",
    "Carmel70@example.com",
    "Caterina82@example.org",
    "Amelia_Gislason49@example.net",
    "Wanda_Bode15@example.com",
    "Felicia76@example.com",
    "Jarrell52@example.net",
    "Marilie.Lebsack@example.com",
    "Christop27@example.com",
    "Bridie.Satterfield@example.org",
    "Hosea36@example.org",
    "Greyson.Jast45@example.com",
    "Eddie_Welch52@example.com",
    "Harold.Breitenberg71@example.net",
    "Rudolph7@example.org",
    "Shanie_Buckridge@example.org",
    "Berneice_Ferry2@example.net",
    "Margarett.Bergstrom17@example.org",
    "Will_Boehm@example.org",
    "Mckayla.Hane@example.org",
    "Ruby80@example.net",
    "Maryam57@example.net",
    "Karson59@example.net",
    "Alysa42@example.org",
    "Yasmin.Tremblay20@example.net",
    "Cordell_Spinka@example.org",
    "Bradly96@example.org",
    "Geoffrey17@example.org"
};

  @Autowired
  private UserRepo userRepo;

  @Autowired
  private PasswordEncoder passwordEncoder;

  @Test
  public void usersInsertTest() {
    for (int i = 0 ; i < 100; i += 1) {
      User user = User.builder()
        .userid(usernames[i])
        .email(emails[i])
        .passwd(passwordEncoder.encode(String.format("password%03d", i)))
        .build();
      user.addRole(Role.USER);
      userRepo.save(user);
    }
    User admin = User.builder().userid("hina").passwd(passwordEncoder.encode("perfect")).email("gehenna@example.com").build();
    userRepo.save(admin);
  }



}
